apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fast-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rmsantis/application-monitoring-prometheus.git
    path: k8s 
    targetRevision: main
  destination:
    namespace: fast-api
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
