apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: rslim087/fastapi-prometheus:latest
        ports:
        - containerPort: 8000
          name: web