apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: monitoring
  labels:
    app: fastapi-app
spec:
  selector:
    app: fastapi-app
  ports:
  - port: 8000
    targetPort: 8000
    name: web
